version: "3.4"
services:
  
  robot:
    build: .  # Esto le dice a Docker que construya la imagen usando el Dockerfile en el directorio actual
    container_name: Beholder-Robot
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8010",
        "--reload",
      ]
    ports:
      - 8010:8010
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    deploy:
      replicas: 5
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "1"