from .implementations.get_calificacion_alumno import get_calificacion_alumno
from .implementations.get_antidoping_colegio_militarizado import get_antidoping_colegio_militarizado
from .implementations.get_calendario_academico_colegio_militarizado import get_calendario_academico_colegio_militarizado
from .implementations.get_credencializacion_colegio_militarizado import get_credencializacion_colegio_militarizado
from .implementations.get_libros_colegio_militarizado import get_libros_colegio_militarizado
from .implementations.get_nss_colegio_militarizado import get_nss_colegio_militarizado
from .implementations.get_uniformes_colegio_militarizado import get_uniformes_colegio_militarizado
from .implementations.get_anexo_solo_director_forja import get_anexo_solo_director_forja
from .implementations.get_cecati_forja import get_cecati_forja
from .implementations.get_guion_forja_padres import get_guion_forja_padres
from .implementations.get_admisiones_colegio_militarizado import get_admisiones_colegio_militarizado
from .implementations.get_info_general_colegio_militarizado import get_info_general_colegio_militarizado
from .implementations.get_inscripciones_colegio_militarizado import get_inscripciones_colegio_militarizado
from .implementations.get_planteles_colegio_militarizado import get_planteles_colegio_militarizado
from .implementations.get_reinscripciones_colegio_militarizado import get_reinscripciones_colegio_militarizado
from .implementations.get_requisitos_admision_colegio_militarizado import get_requisitos_admision_colegio_militarizado
from .implementations.get_ley_educacion_nuevo_leon import get_ley_educacion_nuevo_leon
from .implementations.get_posicionamiento_oficio_sep import get_posicionamiento_oficio_sep
from .implementations.get_protocolo_preventivo_hostigamiento import get_protocolo_preventivo_hostigamiento
from .implementations.get_posicionamiento_caso_dafne import get_posicionamiento_caso_dafne
from .implementations.get_reglamento_oficial import get_reglamento_oficial
from .implementations.get_disciplina import get_disciplina


registered_functions = [
    get_calificacion_alumno,
    get_antidoping_colegio_militarizado,
    get_calendario_academico_colegio_militarizado,
    get_credencializacion_colegio_militarizado,
    get_libros_colegio_militarizado,
    get_nss_colegio_militarizado,
    get_uniformes_colegio_militarizado,
    get_anexo_solo_director_forja,
    get_cecati_forja,
    get_guion_forja_padres,
    get_admisiones_colegio_militarizado,
    get_info_general_colegio_militarizado,
    get_inscripciones_colegio_militarizado,
    get_planteles_colegio_militarizado,
    get_reinscripciones_colegio_militarizado,
    get_requisitos_admision_colegio_militarizado,
    get_ley_educacion_nuevo_leon,
    get_posicionamiento_oficio_sep,
    get_protocolo_preventivo_hostigamiento,
    get_posicionamiento_caso_dafne,
    get_reglamento_oficial,
    get_disciplina
]
