from .implementations.get_calificacion_alumno import get_calificacion_alumno
from .implementations.get_admisiones_colegio_militarizado import get_admisiones_colegio_militarizado
from .implementations.get_info_general_colegio_militarizado import get_info_general_colegio_militarizado
from .implementations.get_inscripciones_colegio_militarizado import get_inscripciones_colegio_militarizado
from .implementations.get_planteles_colegio_militarizado import get_planteles_colegio_militarizado
from .implementations.get_reinscripciones_colegio_militarizado import get_reinscripciones_colegio_militarizado
from .implementations.get_requisitos_admision_colegio_militarizado import get_requisitos_admision_colegio_militarizado
from .implementations.get_ley_educacion_nuevo_leon import get_ley_educacion_nuevo_leon
from .implementations.get_protocolo_preventivo_hostigamiento import get_protocolo_preventivo_hostigamiento
from .implementations.get_posicionamiento_caso_dafne import get_posicionamiento_caso_dafne
from .implementations.get_reglamento_oficial import get_reglamento_oficial
from .implementations.get_disciplina import get_disciplina
from .implementations.get_posicionamiento_caso_dafne import get_posicionamiento_caso_dafne


registered_functions = [
    get_calificacion_alumno,
    get_admisiones_colegio_militarizado,
    get_info_general_colegio_militarizado,
    get_inscripciones_colegio_militarizado,
    get_planteles_colegio_militarizado,
    get_reinscripciones_colegio_militarizado,
    get_requisitos_admision_colegio_militarizado,
    get_ley_educacion_nuevo_leon,
    get_protocolo_preventivo_hostigamiento,
    get_posicionamiento_caso_dafne,
    get_reglamento_oficial,
    get_disciplina,
    get_posicionamiento_caso_dafne
]
