SAN_PEDRO_COLONIES = [
  "Alto Eucalipto",
  "Alto Jazmín",
  "Ampliación Canteras",
  "Ampliación Jardines de San Agustín 3er Sector",
  "Ampliación Lomas del Campestre",
  "Ampliación Valle del Mirador",
  "Antigua Hacienda San Agustin",
  "Balcones Del Campestre",
  "Balcones Del Valle",
  "Balcones de San Agustin",
  "Barranca Del Pedregal",
  "Bosques de La Sierra 1er Sector",
  "Bosques de La Sierra 2do Sector",
  "Bosques de La Sierra 3er Sector",
  "Bosques del Valle 1er Sector",
  "Bosques del Valle 2do Sector",
  "Bosques del Valle 3er Sector",
  "Bosques del Valle 4to Sector",
  "Bosques del Valle 5to Sector",
  "Bosques del Valle Ampliación 5 Sector",
  "Bosques de San Ángel Sector Palmillas",
  "Bugambilias",
  "Casco Urbano",
  "Casco",
  "Capistrano",
  "Carrizalejo",
  "Cerrada Moralillo",
  "Codornices Aldama",
  "Cojunto Habitacional Renzo",
  "Colinas de La Sierra Madre",
  "Colinas de San Agustin",
  "Colinas de San Angel 1er Sector",
  "Colinas de San Ángel 2do Sector",
  "Colonial La Sierra",
  "Colonial San Agustin",
  "Colonia Valle Oriente Sur",
  "Colorines 1er Sector",
  "Colorines 2do Sector",
  "Colorines 3er Sector",
  "Colorines 4to Sector",
  "Colorines 5to Sector",
  "Comercial Alpino Chipinque",
  "Condominio",
  "Corporativo Prodesa",
  "Corporativo Proser",
  "Corporativo Santa Engracia 1 Sector",
  "Corporativo Santa Engracia 2 Sector",
  "Cortijo Del Valle",
  "Del Valle",
  "Del Valle Oriente",
  "Del Valle Sect Norte",
  "Del Valle Sector Fátima",
  "Del Valle Sect Oriente",
  "Echeverría",
  "El Obispo",
  "El Obispo",
  "El Obispo 2",
  "El Refugio",
  "El Santuario",
  "El Secreto",
  "Fátima",
  "Flor de Mayo",
  "Fuentes del David",
  "Fuentes del Valle",
  "Fuentes del Valle Sector Colinas",
  "Gómez Morin",
  "Hacienda de Carrizalejo",
  "Hacienda de La Sierra",
  "Hacienda de los Callejones",
  "Hacienda Del Valle",
  "Hacienda El Rosario",
  "Hacienda las Campanas",
  "Hacienda San Agustin",
  "Jardines Coloniales 1er Sector",
  "Jardines Coloniales 2 Sector",
  "Jardines Coloniales 3er Sector",
  "Jardines de Campestre",
  "Jardines del Campestre",
  "Jardines Del Valle",
  "Jardines de Mirasierra",
  "Jardines de San Agustin 1 Sector",
  "Jardines de San Agustín 2 Sector",
  "Jardines de San Agustín 3 Sector",
  "Jerónimo Siller",
  "Jesús M Garza",
  "Joya del Venado",
  "La Admiranza",
  "La Barranca",
  "La Cañada",
  "La Cima 1er Sector",
  "La Cima 2do Sector",
  "La Cima 3er Sector",
  "La Cooperativa",
  "La Cúspide",
  "La Diana",
  "La Encantada",
  "La Finca",
  "La Joya",
  "La Joya de La Corona",
  "La Leona",
  "La Montaña",
  "La Muralla",
  "La Parvada",
  "Las Alondras",
  "Las Calzadas",
  "Las Capillas",
  "Las Ceibas",
  "Las Codornices",
  "Las Privanzas 3 Sector Segunda Etapa",
  "Las Privanzas Primero",
  "Las Privanzas Segundo",
  "Las Querenzas",
  "Las Sendas Andalucía",
  "Las Sendas Galicias",
  "Las Uvas",
  "Las Verandas",
  "La Ventana",
  "Lázaro Garza Ayala",
  "Lindavista",
  "Loma Blanca",
  "Lomas del Bosque",
  "Lomas del Campestre 1er Sector",
  "Lomas del Campestre 2 Sector",
  "Lomas Del Rosario",
  "Lomas Del Valle",
  "Lomas de San Agustín 1er Sector",
  "Lomas de San Agustín 2 Sector",
  "Lomas de San Agustín 3 Sector",
  "Lomas de San Angel",
  "Lomas de Tampiquito",
  "Lomas Valle Sector Convento",
  "Los Amates",
  "Los Arcángeles",
  "Los Encinos",
  "Los Fresnos",
  "Los Olivos",
  "Los Olmos",
  "Los Pinos 1er Sector",
  "Los Pinos 2 Sector (Asentamiento Irregular)",
  "Los Quetzales",
  "Los Rincones",
  "Los Sauces 1er Sector",
  "Los Sauces 2 Sector",
  "Lucio Blanco 1er Sector",
  "Lucio Blanco 2do Sector",
  "Lucio Blanco 3er Sector",
  "Mansión Del Rosario",
  "Mesa de la Corona",
  "Mirador Del Campestre",
  "Mirador de Vasconcelos",
  "Mirasierra 1er Sector",
  "Mirasierra 2do Sector",
  "Mirasierra 3er Sector",
  "Mirasierra 4to Sector",
  "Mirasierra 5to Sector",
  "Misión Del Valle",
  "Misión del Valle 3",
  "Misión de San Agustín",
  "Misión San Patricio",
  "Moralillo",
  "Morelos",
  "Nemesio Garcia Naranjo",
  "Olímpico",
  "Olinalá",
  "Palo Blanco",
  "Palo Blanco Sector El Edén",
  "Parque Corporativo Uccaly",
  "Pedregal Del Valle",
  "Plan de Ayala",
  "Portal de Santa Engracia",
  "Prados de La Sierra",
  "Privada 20 de Noviembre",
  "Privada Gruta",
  "Privada Lomas de San Agustin",
  "Privada Real de San Agustín",
  "Privada Río Ebro",
  "Privada San Andrés",
  "Privada San Roberto",
  "Privada Santa Engracia",
  "Privada Sierra Madre",
  "Privada Versalles",
  "Privanza Alicante",
  "Privanza Fundadores",
  "Privanzas",
  "Privanzas 4 Sector 1 Etapa",
  "Privanzas Alejandría",
  "Privanzas Burdeos",
  "Privanzas Córcega",
  "Privanzas Marsella",
  "Privanzas Martinica",
  "Privanzas Mónaco",
  "Privanzas Niza",
  "Privanzas Pamplona",
  "Privanza Toledo",
  "Privanza Venecia",
  "Provivienda",
  "Punto Central",
  "Real Del Valle",
  "Real de San Agustin",
  "Residencial Canteras",
  "Residencial Chipinque 1 Sector",
  "Residencial Chipinque 2 Sector",
  "Residencial Chipinque 3 Sector",
  "Residencial Chipinque 4 Sector",
  "Residencial Frida Kahalo",
  "Residencial Galeana",
  "Residencial las Amapas",
  "Residencial Los Cubos",
  "Residencial Palo Blanco",
  "Residencial San Agustin 1 Sector",
  "Residencial San Agustín 2 Sector",
  "Residencial San Carlos",
  "Residencial Santa Bárbara 1 Sector",
  "Residencial Santa Bárbara 2 Sector",
  "Residencial Santa Barbara la Cripta",
  "Residencial Sierra Del Valle",
  "Revolución 1er Sector",
  "Revolución 2do Sector",
  "Revolución 3er Sector",
  "Revolución 4to Sector",
  "Revolución 5to Sector",
  "Rincón Colonial",
  "Rincón de Carrizalejo",
  "Rincón de Corregidora",
  "Rincón de La Montaña 1er Sector",
  "Rincón de la Montaña 2 Sector",
  "Rincón de la Montaña 3 Sector",
  "Rincón de las Garzas",
  "Rincón del Campestre",
  "Rincón de San Francisco",
  "San Agustin Campestre",
  "San Francisco",
  "San Gabriel",
  "San José",
  "San Mateo",
  "San Patricio 1 Sector",
  "San Patricio 2 Sector",
  "San Patricio 3 Sector",
  "San Patricio 4 Sector",
  "San Pedro",
  "San Pedro",
  "San Pedro 400",
  "San Pedro 400 Ampliación Norte",
  "Centro",
  "San Pedro Garza Garcia Centro",
  "Santa Cruz",
  "Santa Elena",
  "Santa Engracia",
  "Santa Fe",
  "Sierra Nevada",
  "Tampiquito",
  "Tampiquito",
  "Turquesa",
  "Unidad Habitacional San Pedro",
  "Valle de Chipinque",
  "Valle Del Campestre",
  "Valle Del Mezquite",
  "Valle del Seminario 1 Sector",
  "Valle del Seminario 2 Sector",
  "Valle de San Agustin",
  "Valle de San Ángel Rincón Francés",
  "Valle de San Ángel Sect Español",
  "Valle de San Angel Sect Frances",
  "Valle de San Ángel Sect Jardines",
  "Valle de San Ángel Sect Mexicano",
  "Valle de Santa Engracia",
  "Valle de Vasconcelos",
  "Veredalta",
  "Verona",
  "Villa Campanario",
  "Villa Chipinque",
  "Villa del Obispo",
  "Villa Del Pedregal",
  "Villa las Palmas",
  "Villa Montaña 1er Sector",
  "Villa Montaña 2 Sector",
  "Villa Montaña Campestre",
  "Villas Carmel",
  "Villas Crisantemo",
  "Villas de Aragón",
  "Villas Del Pedregal",
  "Villas del Valle",
  "Villas de San Agustin",
  "Villas de Santa Bárbara",
  "Villas de Santa Engracia",
  "Villas de Terrasol",
  "Villas La Rivera",
  "Vista Montaña 1er Sector",
  "Vista Montaña 2 Sector",
  "Vista Montaña 3 Sector",
  "Vista Real",
  "Vistas del Valle",
  "Volkswagen",
  "Zona Alpino",
  "Zona Antigua Exhacienda Carrizalejo",
  "Zona Antigua Exhacienda San Agustín",
  "Zona Bosques de la Sierra",
  "Zona Bosques del Valle",
  "Zona Campestre",
  "Zona Carrizalejo",
  "Zona Clouhtier",
  "Zona Colinas Sierra Madre",
  "Zona de Los Callejones",
  "Zona del Valle",
  "Zona el Santuario",
  "Zona Fátima",
  "Zona Fuentes del Valle",
  "Zona Hacienda San Agustín",
  "Zona Hacienda San Francisco",
  "Zona Industrial",
  "Zona Jerónimo Siller",
  "Zona la Alianza",
  "Zona la Cima",
  "Zona la Diana",
  "Zona La Ventana",
  "Zona Loma Blanca",
  "Zona Loma Blanca Poniente",
  "Zona Loma Larga Oriente",
  "Zona Lomas del Campestre",
  "Zona Lomas de San Agustín",
  "Zona los Sabinos",
  "Zona los Sauces",
  "Zona Mirador Vazconcelos",
  "Zona Mirasierra",
  "Zona Montebello",
  "Zona Palo Blanco",
  "Zona Pedregal del Valle",
  "Zona Privada Río Tamazunchale",
  "Zona Residencia Chipinque",
  "Zona Revolución",
  "Zona Rosario",
  "Zona San Agustín",
  "Zona San Agustín Campestre",
  "Zona San Patricio 3 Sector",
  "Zona San Patricio 4 Sector",
  "Zona Santa Bárbara Poniente",
  "Zona Santa Engracia",
  "Zona Tampiquito",
  "Zona Valle del Mezquite",
  "Zona Valle Oriente Norte",
  "Zona Valle Oriente Sur",
  "Zona Valle Poniente",
  "Zona Valle San Ángel",
  "Zona Valle Santa Engracia"
]