SAN_PEDRO_STREETS_REAL = [
    '1', '13 De Septiembre', '16 De Septiembre', '2', '20 De Noviembre', '21 De Marzo', '2 De Abril', '3', '5 De Mayo',
    'Abedul', 'Abeto', 'Acequia', 'Acuerdos', 'Adán Hernández Rojas', 'Adolfo De La Huerta', 'Agua Marina',
    'Aguascalientes', 'Águila', 'Agustín Siller', 'Alabastro', 'Álamo', 'Álamos', 'Alberto C. Siller', 'Alcázar',
    'Alce', 'Alejandría', 'Alejandro Vi', 'Alfonso Reyes', 'Alfredo Verástegui', 'Alhambra', 'Alicia', 'Allende',
    'Almadén', 'Alto Claro', 'Aluminio', 'Álvaro Obregón', 'Amatista', 'América', 'Amistad', 'Anacleto Guerrero',
    'Ana Cristina', 'Anáhuac', 'Anastasio Rodríguez Carvajal', 'Andador Corregidora', 'Andador Del Sol',
    'Antigua Carretera A Chipinque', 'Antiguo Camino', 'Antiguo Camino San Agustín', 'Antiguo Camino San Agustín Poniente',
    'Antilope', 'Antimonio', 'Antioquia', 'Antonio', 'Antonio De S.', 'Antonio Díaz Soto', 'Antonio I. Villarreal',
    'Antonio López', 'Apeninos', 'Aquiles Serdán', 'Aramberri', 'Aranjuez', 'Árbol', 'Arboledas', 'Arco Constantino',
    'Arco Del Triunfo', 'Arcos', 'Aristóteles', 'Armenia', 'Arquímedes', 'Arroyo', 'Artículo 27', 'Arturo B. De La Garza',
    'Atenas', 'Atotonilco', 'Avenida Cenizo', 'Azalea', 'Aztlán', 'Azucena', 'Azufre', 'Babilonia', 'Balcones',
    'Baptisterio', 'Barcelona', 'Barranca', 'Basalto', 'Batallones Rojos', 'Batallón San Patricio', 'Begonia',
    'Belisario Domínguez', 'Benito J. Feijoo', 'Benito Juárez', 'Benjamín Hill', 'Bernardino De Sahagún', 'Berrendo',
    'Bizancio', 'Boro', 'Bosque', 'Bosque De Ébanos', 'Bosques De Almendro', 'Bosques De Austria', 'Bosques De Bolonia',
    'Bosques De Campeche', 'Bosques De Canadá', 'Bosques De Caobas', 'Bosques De Catemaco', 'Bosques De Cedros',
    'Bosques De Chapultepec', 'Bosques De Chiapas', 'Bosques De Cuernavaca', 'Bosques De Encinos', 'Bosques De Francia',
    'Bosques De Granados', 'Bosques De Irlanda', 'Bosques De La Huasteca', 'Bosques Del Álamo', 'Bosques De La Sierra',
    'Bosques Del Edén', 'Bosques Del Himalaya', 'Bosques Del Istmo', 'Bosques Del Olivo', 'Bosques De Los Alpes',
    'Bosques De Los Pinos', 'Bosques De Los Pirineos', 'Bosques Del Tíbet', 'Bosques Del Valle', 'Bosques De Mimbres',
    'Bosques De Noruega', 'Bosques De Olmos', 'Bosques De Pirineos', 'Bosques De Puebla', 'Bosques De Saigón',
    'Bosques De Siberia', 'Bosques De Tahití', 'Bosques De Tehuantepec', 'Bosques De Toluca', 'Bosques De Viena',
    'Bosques Negro', 'Bosques Nórdicos', 'Brillantes', 'Bugambilia', 'Bura', 'Bustamante', 'Cádiz', 'Callejas',
    'Callejón 1', 'Callejón 2', 'Callejón 3', 'Callejón 4', 'Callejón 6', 'Callejón Capellanía', 'Callejón De Las Alondras',
    'Callejón De Las Privanzas', 'Callejón Del Lobo', 'Callejón De Los Arizpe', 'Callejón De Los Ayala', 'Calzada De Los Cedros',
    'Calzada De Los Cipreses', 'Calzada De Los Encinos', 'Calzada De Los Maples', 'Calzada De Los Olmos', 'Calzada Del Valle',
    'Camelia', 'Camilo Flammarion', 'Camino Real', 'Campestre', 'Campos Elíseos', 'Cañada', 'Candelaria', 'Canelo',
    'Cantera', 'Caoba', 'Capellanía', 'Capri', 'Carbono', 'Carlos Mérida', 'Carranza', 'Carretera A Chipinque',
    'Carrizalejo', 'Cartagena', 'Casa Blanca', 'Cascada', 'Casolar', 'Castillo De Chambort', 'Cedro', 'Cedros',
    'Ceniza', 'Centaya', 'Central', 'Cerezo', 'Cerrada De Encino', 'Cerrada De Los Olmos', 'Cerrada Los Nogales',
    'Cerrada Santander Poniente', 'Cerro', 'Cerro Blanco', 'Cerro De La Luz', 'Cerro De La Silla', 'Cerro De Las Mitras',
    'Cerro Del Mirador', 'Cerro De Picachos', 'Cerro Prieto', 'Cerro Tuera', 'Chapultepec', 'Chimalistac', 'Chimborazo',
    'Chopos', 'Cicerón', 'Ciervo', 'Cimarrón', 'Ciprés', 'Cipreses', 'Circón', 'Circunvalación', 'Cirene', 'Ciruelo',
    'Clara', 'Clavel', 'Coapa', 'Cobalto', 'Cobre', 'Cocoyoc', 'Cofre De Perote', 'Colina Azul', 'Colonial De La Sierra',
    'Colorines', 'Cóndor', 'Conquistadores', 'Convento', 'Copilco', 'Coral', 'Cordillera', 'Córdova', 'Corinto',
    'Corona', 'Corporativo', 'Corregidora', 'Corregidora Norte', 'Corregidora Sur', 'Coruña', 'Coyoacán', 'Crisantema',
    'Cristal', 'Cristóbal Colón', 'Cromo', 'Cuarzo', 'Cuauhtémoc', 'Dalila', 'Dal Monte', 'Damasco', 'Daniel Dávila O.',
    'David Alfaro Siqueiros', 'Dávila Reyes', 'Decápolis', 'Degollado', 'Degollado Norte', 'Degollado Sur', 'De La Cañada',
    'De La Industria', 'De Las Canteras', 'De Las Magnolias', 'De Las Privanzas', 'De Las Sierras', 'Del Caballo',
    'Del Callejón', 'Del Campo', 'Del Cedro', 'Del Ciprés', 'Del Comercio', 'Del Encino', 'De Los Acuerdos', 'De Los Álamos',
    'De Los Apóstoles', 'De Los Arcángeles', 'De Los Ayala', 'De Los Cedros', 'De Los Conquistadores', 'De Los Eucaliptos',
    'De Los Nogales', 'De Los Olivos', 'De Los Olmos', 'De Los Pinos', 'De Los Sabinos', 'De Los Santos', 'De Los Sauces',
    'Del Paricutín', 'Del Peñón', 'Del Refugio', 'Del Retorno', 'Del Rosario', 'Del Sauce', 'Del Valle',
    'Del Valle Alberto Santos', 'De San Patricio', 'Descartes', 'Diamante', 'Diego De Almagro', 'Diego De Montemayor',
    'Diego Rivera', 'Diego Saldívar', 'División Del Norte', 'Doblado', 'Doctor Atl', 'Doctor E. Rangel', 'Doctor Ricardo Ortega',
    'Doctor R. S. Sepúlveda', 'Don Quijote', 'Dublín Oriente', 'Dublín Poniente', 'Duomo', 'Ébano', 'Ébanos', 'El Árbol',
    'El Arroyo', 'El Caído', 'El Granero', 'El Huerto', 'El Laurel', 'El Rosario', 'Emilia', 'Emilio Carranza', 'Encino',
    'Encino Rojo', 'Encinos', 'Encino Verde', 'Enrique García Leal', 'Enrique Herrera', 'Enrique Ramírez', 'Epigmenio García',
    'Escalones', 'Escorial', 'Esmeralda', 'Esperanza', 'Estaño', 'Esteban V', 'Eucalipto', 'Eugenio Garza La Güera',
    'Eulalio Guzmán', 'Everardo Sosa', 'Félix I.', 'Fernando Dávila Reyes', 'Fernando Magallanes', 'Fierro', 'Florencia',
    'Fluor', 'Fontana Di Tredi', 'Foro Romano', 'Framboyanes Norte', 'Framboyanes Sur', 'Francisco Cárdenas',
    'Francisco Carvajal', 'Francisco I. Madero', 'Francisco Pizarro', 'Francisco Siller', 'Francisco Villa', 'Franco',
    'Fray Juan De Zumárraga', 'Fresno', 'Fresnos', 'Frida', 'Frida Kahlo', 'Fuentes', 'Fuentes Del Valle', 'Gacela',
    'Galatea', 'Garante', 'Gardenia', 'Garza Botello', 'Genaro Garza García', 'General Álvaro Obregón', 'General Bernardo Reyes',
    'General Emiliano Zapata', 'General Felipe Ángeles', 'General Francisco Naranjo', 'General Francisco Villa',
    'General Gerónimo Treviño', 'General Gerónimo Treviño 2', 'General Ignacio Zaragoza', 'General Jerónimo Treviño',
    'General Jerónimo Treviño 1', 'General Manuel González Rangel', 'General Pablo González Garza', 'General Porfirio Díaz',
    'General Vicente Guerrero', 'Genoveva', 'Gertrudis', 'Girasol', 'G. J. De Quezada', 'Gladiola', 'Gómez Morín',
    'Gonzalo J. De Quezada', 'Grafito', 'Granada', 'Granado', 'Granados', 'Granate', 'Granito', 'Grecia', 'Gruta',
    'Gruta Azul', 'Guayalejo', 'Guillermo Prieto', 'Hacienda De Carrizalejo', 'Hacienda De Icamole', 'Hacienda De La Sierra',
    'Hacienda Del Ayancual', 'Hacienda Del Valle', 'Hacienda De Sabarado', 'Hacienda Villa Vieja', 'Halcón',
    'Héctor Serna Uribe', 'Helio', 'Hermanos Serdán', 'Hermenegildo Galeana', 'Hernán Cortés', 'Hidalgo', 'Himalaya',
    'Hortelanos', 'Hoyo Cinco', 'Hoyo Cuatro', 'Hoyo Diez', 'Hoyo Dos', 'Hoyo Nueve', 'Hoyo Ocho', 'Hoyo Once',
    'Hoyo Seis', 'Hoyo Siete', 'Hoyo Tres', 'Hoyo Uno', 'Hualahuises', 'Huasteca', 'Humberto Junco Voigt', 'Humberto Lobo',
    'Icotu', 'Ignacio Allende', 'Ignacio Altamirano', 'Ignacio Manuel Altamirano', 'Ignacio Morones Prieto', 'Independencia',
    'Ingeniero Alberto R. González', 'Ingeniero Arturo B. Gónzalez', 'Ingeniero Carlos Bazan', 'Ingeniero Florentino Arroyo',
    'Ingeniero Francisco Beltrán', 'Ingeniero Juan Crouset', 'Ingeniero Lidio A. Torres', 'Jacaranda', 'Jade', 'Jaguarundi',
    'Jalisco', 'Janitzio', 'Jardines Coloniales', 'Jazmín', 'Jerez', 'Jericó', 'Jerónimo Savoranola', 'Jerónimo Siller',
    'Jesús Mata Garza', 'Jorge P. Garza', 'José Calasanz', 'José Clemente Orozco', 'Josemaría Escrivá', 'José María Maytorena',
    'José María Morelos', 'José María Morelos Y Pavón', 'José Mariano Abasolo', 'José Mariano Jiménez', 'José María Velázquez',
    'José M. Montemayor', 'José Vasconcelos', 'José Vivanco', 'Joya Del Venado', 'Juan Frías', 'Juan González',
    'Juan Ignacio Ramón', 'Juan Sarabia', 'Juárez', 'Junipero Serra', 'Justo Sierra', 'La Alianza', 'Labastida', 'La Cañada',
    'La Ceiba', 'La Cripta', 'La Cuspide', 'Ladera', 'La Escondida', 'La Fragua', 'La Gloria', 'La Hacienda', 'La Herradura',
    'La Joya', 'La Mancha', 'La Meseta', 'Lampazos', 'Landon', 'La Paz', 'La Purísima', 'Laredo', 'La Rivera', 'Las Campanas',
    'Las Codornices', 'Las Diligencias', 'La Sierra', 'Las Moras', 'Las Olimpiadas', 'Las Palmas', 'Las Puentes', 'Las Sendas',
    'Las Torres', 'Las Uvas', 'Laurel', 'La Ventana', 'Lázaro Cárdenas', 'Lázaro Garza Ayala', 'Leonardo Da Vinci', 'Libertad',
    'Librado Rivera', 'Licenciado Adolfo López Mateos', 'Licenciado Adolfo Ruiz Cortines', 'Licenciado Benito Juárez',
    'Licenciado Gustavo Díaz Ordaz', 'Licenciado José Benítez', 'Licenciado Miguel Alemán Valdés', 'Licenciado Verdad',
    'Lima', 'Limón', 'Linares', 'Lince', 'Lirios', 'Litio', 'Lolita', 'Loma', 'Loma Blanca', 'Loma De Los Pinos', 'Lomas',
    'Lomas De Chapultepec', 'Lomas De Jardín', 'Lomas Del Álamo', 'Lomas De La Sierra', 'Lomas Del Bosque', 'Lomas Del Campestre',
    'Lomas Del Campo', 'Lomas Del Cedro', 'Lomas Del Ciprés', 'Lomas Del Encino', 'Lomas Del Fresno', 'Lomas Del Laurel',
    'Lomas Del Manzano', 'Lomas Del Mar', 'Lomas Del Mirador', 'Lomas Del Nogal', 'Lomas Del Pedregal', 'Lomas Del Río',
    'Lomas Del Roble', 'Lomas Del Rosario', 'Lomas Del Sol', 'Lomas Del Valle', 'Lomas De Palo Blanco', 'Lomas De San Agustín',
    'Lomas De San Francisco', 'Lomas De San Javier', 'Lomas De San Jorge', 'Lorena', 'Los Álamos', 'Los Aldama', 'Los Amates',
    'Los Ángeles', 'Los Ángeles Norte', 'Los Ángeles Sur', 'Los Barragán', 'Los Cedros', 'Los Cipreses', 'Los Encinos',
    'Los Fresnos', 'Los Nogales', 'Los Olivos', 'Los Pinos', 'Los Portales', 'Los Rayones', 'Los Rosales', 'Los Sabinos',
    'Los Sauces', 'Los Soles', 'Los Tules', 'Lourdes', 'Louvre', 'Lucerna', 'Lucio Blanco', 'Lucrecia Torin', 'Lugo',
    'Luis Arizpe', 'Luis Cabrera', 'Luis García', 'Madrid', 'Magallanes', 'Magdalena', 'Magnesio', 'Magnolia', 'Málaga',
    'Mallorca', 'Manganeso', 'Manuel Doblado', 'Manuel Gómez Morín', 'Manuel González', 'Manuel Huerta', 'Manuel J. Clouthier',
    'Manuel Rivera Anaya', 'Manuel Santos', 'Manuel Vargas Ayala', 'Manuel Z. Gómez', 'Manzanares', 'Manzanilla', 'Maple',
    'Mar Adriático', 'Mar Aral', 'Marbella', 'Mar Caspio', 'Marco Tulio', 'Mar De Arabia', 'Mar De Bering', 'Mar Del Norte',
    'Mar Egeo', 'Marga', 'Margarita', 'Margay', 'María Cantú Treviño', 'María De Los Ángeles', 'María Izquierdo',
    'Mariano Escobedo', 'Mariano Matamoros', 'Mariano Verastegui', 'Mar Ibérico', 'Mar Mediterráneo', 'Mármol', 'Mar Muerto',
    'Mar Rojo', 'Marsella', 'Matancillas', 'Mater', 'Mercurio', 'Meseta', 'México 68', 'Mezquitales', 'Mezquite', 'Mica',
    'Miguel Ángel', 'Miguel De Cervantes', 'Miguel Hidalgo Y Costilla', 'Mirador Campestre', 'Mirador De Coatzacoalcos',
    'Mirador De La Loma', 'Mirador De La Sierra', 'Mirador Del Valle', 'Mirador San Agustín', 'Mirador Sierra Madre',
    'Misión Del Rosario', 'Misión Del Valle 1', 'Misión Del Valle 2', 'Misión De Monterrey', 'Misión De San Bernardino',
    'Misión De San Diego', 'Misión De San Francisco De Asís', 'Misión De San Jacinto', 'Misión De San Joaquín',
    'Misión De San Juan Capistrano', 'Misión De Santa Ana', 'Misión De Santa Anita', 'Misión De Santa Clara',
    'Misión De Santo Tomás', 'Misión San Patricio', 'Modesto Arreola', 'Molday', 'Molino Del Rey', 'Mónaco', 'Monparnase',
    'Monparnases', 'Monserrat', 'Monte Aconcagua', 'Monte Ancohuma', 'Monte Aventino', 'Montebello', 'Monte Blanco',
    'Monte Capitolio', 'Monte Casino', 'Monte Cervino', 'Monte Donn', 'Monte Esquilino', 'Monte Everest', 'Monte Falco',
    'Monte Huascarán', 'Monte Kilimanjaro', 'Monte Martre', 'Montemorelos', 'Monte Olimpo', 'Monte Palatino',
    'Monte Palatino Norte', 'Monte Palatino Sur', 'Monte Parinacota', 'Monte Parnaso', 'Monte Pedro', 'Monte Pirineos',
    'Monte Platino', 'Monte Platino Sur', 'Monte Quirinal', 'Monte Rosa', 'Monte Saint Michel', 'Montes Altos',
    'Monte San Elías', 'Monte Santa Elena', 'Montes Apalaches', 'Montes Apalaches Sur', 'Montes Cárpatos', 'Montes Celestes',
    'Montes Himalaya', 'Montes Rocallosos', 'Montes Urales', 'Monte Tolima', 'Monte Viminal', 'Mont Matre', 'Montserrat',
    'Mora', 'Moralillo', 'Motolinía', 'Múnich 72', 'Murcia', 'Nápoles', 'Naranjo', 'Nardo', 'Natividad García',
    'Neil Armstrong', 'Nestor García', 'Néstor García', 'Nevado De Colima', 'Nevado De Toluca', 'Nicéforo Zambrano',
    'Ninguno', 'Niños Héroes', 'Níquel', 'Níspero', 'Niza', 'Nochebuena', 'Nogal', 'Noruega', 'Notre Dame', 'Nueva',
    'Nueva Galicia', 'Nueva Vizcaya', 'Nuevo León', 'Ocelote', 'Olivo', 'Olivos', 'Olmos', 'Ónix', 'Ópalo', 'Orense',
    'Oriente', 'Oro', 'Orquídea', 'Pablo O\'higgins', 'Padre Mier', 'Palermo', 'Palma', 'Palmas', 'Palmira', 'Palo Blanco',
    'Pánfilo De Narváez', 'Pánfilo Nájera', 'Pánfilo Narváez', 'Paraíso', 'Paras', 'Parinacota', 'Parte Aguas',
    'Parvada 1000', 'Parvada 600', 'Parvada 800', 'Pascal', 'Paseo Adriana', 'Paseo Ana María', 'Paseo Belinda',
    'Paseo Blanca Celia', 'Paseo Del Molino', 'Paseo De Los Olmos', 'Paseo Del Rosario', 'Paseo Del Seminario',
    'Paseo Elisa', 'Paseo Elizabeth', 'Paseo Esperanza', 'Paseo Gabriela', 'Paseo Irma', 'Paseo María Elena', 'Paseo Olga',
    'Pasionaria', 'Paso De Las Águilas Norte', 'Paso De Las Águilas Sur', 'Paso De La Sierra', 'Pedregal', 'Pedro Alvarado',
    'Pedro Coronel', 'Pedro M. Perales', 'Pedro N. Perales', 'Pedro Ramírez Vázquez', 'Pedro Reyes Zúñiga', 'Pedro Valdivia',
    'Peñas', 'Pera', 'Pericles', 'Perseverancia', 'Pico De Orizaba', 'Pico De Tancitaro', 'Pilar', 'Pilón', 'Pinos',
    'Plan De Ayala', 'Plan De Guadalupe', 'Plan Del Río', 'Plata', 'Platino', 'Platino 400', 'Platón', 'Plaza De San Marcos',
    'Plaza De Venecia', 'Plaza San Marcos', 'Plomo', 'Plutarco Elías Calles', 'P. Moya', 'Poniente', 'Pontevedra',
    'Porfido', 'Porfirio González', 'Potasio', 'Primera Privada San Francisco', 'Primera San Francisco', 'Prisca',
    'Prisciliano Siller', 'Privada Aluminio', 'Privada Centenario', 'Privada Corregidora', 'Privada Gante',
    'Privada Hernández', 'Privada Herradura', 'Privada Isaac Garza', 'Privada Jacaranda', 'Privada Monte Everest',
    'Privada Parque', 'Privada Platino', 'Privada Real De San Agustín', 'Privada Roble', 'Privada San Diego',
    'Privada San José', 'Privada Sierra Azul', 'Privada Sierra Madre', 'Privada Suchiate', 'Privada Sur',
    'Privanza Alejandría', 'Privanza Alicante', 'Privanza Burdeos', 'Privanza Córcega', 'Privanza Fundadores',
    'Privanza Marcella', 'Privanza Martinica', 'Privanza Mónaco', 'Privanza Niza', 'Privanza Pamplona', 'Privanza Toledo',
    'Privanza Venecia', 'Profesora Enedina García', 'Profesora Trinidad Dávila', 'Prolongación Jiménez', 'Prolongación Ladera',
    'Prolongación Lomas Del Sol', 'Prolongación Riolita', 'Puebla', 'Puma', 'Quetzal', 'Rafael Galván', 'Rafael Sanzio',
    'Ramiro Tamez', 'Raúl Rangel Frías', 'Real Del Valle', 'Real De Mallorca', 'Real De Márquez', 'Real De Palma',
    'Real De San Agustín', 'Real San Agustín', 'Reforma', 'Reno', 'Ricardo Flores Magón', 'Ricardo Margáin Zozaya',
    'Rincón De La Huasteca', 'Rincón De La Sierra', 'Rincón De Las Mitras', 'Rincón Del Pinal', 'Rincones', 'Río Akumal',
    'Río Amacuzac', 'Río Amazonas', 'Río Atoyac', 'Río Atuyac', 'Río Balsas', 'Río Blanco', 'Río Bravo', 'Río Brenta',
    'Río Caura', 'Río Colorado', 'Río Conchos', 'Río Danubio', 'Río De La Plata', 'Río Don', 'Río Ebro', 'Río Elba',
    'Río Éufrates', 'Río Ganges', 'Río Grijalva', 'Río Guadalquivir', 'Río Guayalejo', 'Río Hudson', 'Río Jordán',
    'Río La Silla', 'Río Las Palmas', 'Riolita', 'Río Loira', 'Río Lys', 'Río Lyz', 'Río Madeira', 'Río Manzanares',
    'Río Marín', 'Río Mayo', 'Río Mississipi', 'Río Missouri', 'Río Moctezuma', 'Río Molday', 'Río Mosa', 'Río Mosela',
    'Río Navia', 'Río Nazas', 'Río Necaxa', 'Río Neser', 'Río Nilo', 'Río Orinoco', 'Río Pantepec', 'Río Pánuco',
    'Río Papagayos', 'Río Papaloapan', 'Río Paraná', 'Río Pesquería', 'Río Pilón', 'Río Potomac', 'Río Potosí',
    'Río Presas', 'Río Purificación', 'Río Ramos', 'Río Rhin', 'Río Ródano', 'Río Rosas', 'Río Salado', 'Río Salinas',
    'Río San Joaquín', 'Río San Juan', 'Río San Lorenzo', 'Río San Marcos', 'Río San Martín', 'Río Sena', 'Río Suchate',
    'Río Suchiate', 'Río Suchil', 'Río Tajo', 'Río Tamazunchale', 'Río Tamesi', 'Río Támesis', 'Río Tamuín', 'Río Tiber',
    'Río Tigris', 'Río Tonalá', 'Río Tuxpan', 'Río Usumacinta', 'Río Villagrán', 'Río Vistula', 'Río Volga', 'Río Weser',
    'Río Yaqui', 'Río Yukón', 'Risco', 'Riscos', 'Roberto Garza Sada', 'Roble', 'Rodolfo Gaytán', 'Roque González Garza',
    'Rosa', 'R. Tuxtepec', 'Rubí', 'Rufino Tamayo', 'Sabino', 'Saint Mitchel', 'Samaria', 'San Agustín', 'San Alberto',
    'San Andrés', 'San Ángel', 'San Antonio', 'San Antonio Bexar', 'San Bernardino', 'San Carlos', 'San Clemente',
    'San Evaristo', 'San Felipe De Jesús', 'San Felipe De Linares', 'San Fernando', 'San Francisco', 'San Isidro',
    'San José', 'San Juan', 'San Juan Capistrano Oriente', 'San Lorenzo', 'San Pablo', 'San Patricio', 'San Pedro',
    'San Pedro Norte', 'San Pedro Sur', 'San Roberto', 'Santa Anita', 'Santa Bárbara', 'Santa Catarina', 'Santa Cecilia',
    'Santa Cecilia Oriente', 'Santa Cruz', 'Santa Elena', 'Santa Engracia', 'Santa Engracia Margáin', 'Santa Esperanza',
    'Santa Fe', 'Santa Ilusión', 'Santa Isabel Sur', 'Santa Lucía', 'Santa Magdalena', 'Santa María', 'Santa Mariana',
    'Santa Martha Norte', 'Santa Martha Oriente', 'Santa Martha Poniente', 'Santa Martha Sur', 'Santa Mónica', 'Santander',
    'Santander Poniente', 'Santa Paulina', 'Santa Regina', 'Santa Rita', 'Santa Rosa', 'Santa Sofía', 'Santiago', 'Sauces',
    'Saúcos', 'Sebastián Benalcázar', 'Sebastián Lerdo De Tejada', 'Segunda San Francisco', 'Sendero Blanco',
    'Sendero De Las Alondras', 'Sendero De Las Privanzas', 'Servidumbre Del Paso', 'Sevilla', 'Sierra Alta', 'Sierra Azul',
    'Sierra Baja', 'Sierra Bellas', 'Sierra Chica', 'Sierra De Ajusco', 'Sierra De Juárez', 'Sierra De La Gavia',
    'Sierra Del Ajusco', 'Sierra Del Carmen', 'Sierra Del Pino', 'Sierra Del Sol', 'Sierra Del Valle', 'Sierra De María',
    'Sierra De Picachos', 'Sierra De Tarahumara', 'Sierra De Taxco', 'Sierra De Zitácuaro', 'Sierra El Pinal', 'Sierra Fría',
    'Sierra Hermosa', 'Sierra Leona', 'Sierra Linda', 'Sierra Mijes', 'Sierra Milcumbres', 'Sierra Mojada', 'Sierra Morena',
    'Sierra Negra', 'Sierra Nevada', 'Sierra Rosa', 'Sierra Sagra', 'Sierra Verde', 'Sierra Vertientes', 'Simón De La Garza Melo',
    'Sócrates', 'Sodio', 'Suchiate', 'Tabachín', 'Tajín', 'Talco', 'Talud', 'Tamaulipas', 'Tamazate', 'Tamazunchale',
    'Taxqueña', 'Tecamachalco', 'Tecate', 'Temístocles', 'Tenayuca', 'Tenochtitlan', 'Teocalli', 'Teotihuacan',
    'Terminal Monparnases', 'Terrasol', 'Texcoco', 'Tiburtina', 'Ticomán', 'Tigre', 'Titanio', 'Tixco', 'Tokio 64',
    'Toledo', 'Topacio', 'Torre De Pisa', 'Torre Eiffel', 'Torrevillas', 'Toulouse', 'Treviño', 'Tulipán', 'Tungsteno',
    'Turquesa', 'Tuxtepec', 'Uranio', 'Usumacinta', 'Uxmal', 'Valencia', 'Valentín G. Rivero', 'Valeria', 'Valladolid',
    'Valle Blanco', 'Valle De Chipinque', 'Valle De La Paz', 'Valle Del Mezquite', 'Valle San Ángel', 'Valle Sol',
    'Vasconcelos', 'Venado', 'Venecia', 'Vereda De Las Privanzas', 'Versalles', 'Vía Aemilia', 'Vía Angélica', 'Vía Appia',
    'Vía Aremula', 'Vía Asinaria', 'Vía Augusta', 'Vía Borelli', 'Vía Caecilia', 'Vía Clodia', 'Vía Collatina', 'Vía Corso',
    'Vía Curso Oriente', 'Vía Flamina', 'Vía Gabina', 'Vía Galvani', 'Vía Julio César', 'Vía Labicana', 'Vía Láctea',
    'Vía Latina', 'Vía Ludovise', 'Vía Ostiensis', 'Vía Popilia', 'Vía Rómulo', 'Vía Sacra', 'Vía Salaria', 'Vía Sannio',
    'Vía Savotino', 'Vía Servio Tulio', 'Vía Settembre', 'Vía Sistina', 'Vía Tito Flavio', 'Vía Triumphalis', 'Vía Triunfa',
    'Vía Valeria', 'Víctor Hugo', 'Viena', 'Viento Blanco', 'Vigo', 'Villa De Chipinque', 'Villa Fontana', 'Villaldama',
    'Villas De Santa Engracia', 'Villa Ventana', 'Violeta', 'Virgilio Cárdenas', 'Vista Condesa', 'Vista Duquesa',
    'Vista Escorial', 'Vista Excelsa', 'Vista Imperial', 'Vista Magna', 'Vista Marquesa', 'Vista Monarca', 'Vista Real',
    'Vista Regia', 'Vista Señorial', 'Vista Soberana', 'Vista Sublime', 'Vista Suprema', 'Volcán', 'Xalostoc', 'Xochicalco',
    'Yodo', 'Zacatenco', 'Zafiro', 'Zinc'
]